sudo: required
services:
  - docker
before_install:
  - docker build -t tajpouria/swagger-codegen -f ./Dockerfile .
script:
  - docker run tajpouria/swagger-codegen npm run test
  - docker run tajpouria/swagger-codegen npm run lint
deploy:
  provide: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: 'v0.0.1'
branches:
  except:
    - 'v0.0.1'
